use HR_system;
insert into USERS value ('admin1','12345','liza','grishkina','ADMIN',0);
insert into USERS value ('user3','12ab','Alla','Summer','USER',1);
insert into USERS value ('admin2','abc','alina','belaya','ADMIN',0);
insert into USERS value ('user1','123','Mihail','Fedorov','USER',1);
insert into USERS value ('user2','123','Evgen','Gusev','USER',0);
insert into USERS value ('user4','qwerty','Melody','Pond','USER',0);
insert into USERS value ('user5','asd','River','Song','USER',1);
insert into USERS value ('user8','123','Rory','Yilwiams','USER',1);
insert into USERS value ('user7','poiuy','Inna','Petrova','USER',-1);
insert into USERS value ('user6','mnbvc','Clara','Oswald','USER',0);
insert into USERS value ('admin3','123789','Bella','Swan','ADMIN',0);